version: '3'

services:
  micro-consumer:
    build: micro-consumer/
    depends_on:
      - "database"
      - "sqs"
    links:
    - "database"
    - "sqs"
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
  sqs:
    image: feathj/fake-sqs
    ports:
      - "9494:9494"
    environment:
      VIRTUAL_HOST: "sqs.docker"
