version: '3'

services:
  micro-consumer:
    build: micro-consumer/
    depends_on:
      - "database"
    links:
      - "database"
  micro-updator:
    build: micro-updator/
    depends_on:
      - "database"
      - "micro-consumer"
    links:
      - "database"
    env_file:
      - "docker-env-vars.env"
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
