version: '3'

services:
  history:
    build: .
    depends_on:
      - "database"
    ports:
      - "3000:3000"
    links:
    - "database"
    - "statsd"
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
  statsd:
    image: hopsoft/graphite-statsd
    ports:
      - "3002:80"
      - "2003:2003"
      - "8125:8125/udp"
  grafana:
    image: grafana/grafana
    links:
      - statsd
    ports:
      - "3001:3000"
